service: serverless-boilerplate

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.stageDefault}
  region: eu-central-1
  credentials: ${self:custom.${self:provider.stage}.credentials}
  stackTags:
      client: XXCLIENT
      project: XXPROJECT

custom:
  stageDefault: local
  webpackDefault: webpack.config.js
  webpack: ${opt:config, self:custom.webpackDefault}
  local: ${file(./serverless/local.yml)}

functions:
  test:
    handler: handler.testHandler
    events:
      - http:
          path: test/{type}
          method: get
          cors: true